name: 'Format Java Code'
description: 'Runs mvn spotless:apply'
inputs:
  path:
    description: 'Path to the java repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 11 for formatting
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v4.2.1
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.0.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles(format('{0}/**/pom.xml', inputs.path)) }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Run Spotless Apply
      run: mvn spotless:apply
      shell: bash
      working-directory: ${{ inputs.path }}
