name: 'Format Java Code'
description: 'Runs mvn spotless:apply'
inputs:
  path:
    description: 'Path to the java repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up JDK for formatting
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@b7e8d49f17405cc70c1c120101943203c98d3a4b
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles(format('{0}/**/pom.xml', inputs.path)) }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Run Spotless Apply
      run: mvn spotless:apply
      shell: bash
      working-directory: ${{ inputs.path }}
