language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk7

#travis_wait : avoid time out
install: travis_wait mvn install -Dgpg.skip=true

sudo: false

after_success:
  - mvn clean test jacoco:report coveralls:report
