/*
 * Authentication webhooks
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.acswebhooks;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;

/** RelayedAuthenticationResponse */
@JsonPropertyOrder({RelayedAuthenticationResponse.JSON_PROPERTY_AUTHENTICATION_DECISION})
public class RelayedAuthenticationResponse {
  public static final String JSON_PROPERTY_AUTHENTICATION_DECISION = "authenticationDecision";
  private AuthenticationDecision authenticationDecision;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetAuthenticationDecision = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public RelayedAuthenticationResponse() {}

  /**
   * authenticationDecision
   *
   * @param authenticationDecision
   * @return the current {@code RelayedAuthenticationResponse} instance, allowing for method
   *     chaining
   */
  public RelayedAuthenticationResponse authenticationDecision(
      AuthenticationDecision authenticationDecision) {
    this.authenticationDecision = authenticationDecision;
    isSetAuthenticationDecision = true; // mark as set
    return this;
  }

  /**
   * Get authenticationDecision
   *
   * @return authenticationDecision
   */
  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_DECISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AuthenticationDecision getAuthenticationDecision() {
    return authenticationDecision;
  }

  /**
   * authenticationDecision
   *
   * @param authenticationDecision
   */
  @JsonProperty(JSON_PROPERTY_AUTHENTICATION_DECISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticationDecision(AuthenticationDecision authenticationDecision) {
    this.authenticationDecision = authenticationDecision;
    isSetAuthenticationDecision = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public RelayedAuthenticationResponse includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this RelayedAuthenticationResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelayedAuthenticationResponse relayedAuthenticationResponse = (RelayedAuthenticationResponse) o;
    return Objects.equals(
        this.authenticationDecision, relayedAuthenticationResponse.authenticationDecision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationDecision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelayedAuthenticationResponse {\n");
    sb.append("    authenticationDecision: ")
        .append(toIndentedString(authenticationDecision))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetAuthenticationDecision) {
      addIfNull(nulls, JSON_PROPERTY_AUTHENTICATION_DECISION, this.authenticationDecision);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of RelayedAuthenticationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RelayedAuthenticationResponse
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     RelayedAuthenticationResponse
   */
  public static RelayedAuthenticationResponse fromJson(String jsonString)
      throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, RelayedAuthenticationResponse.class);
  }

  /**
   * Convert an instance of RelayedAuthenticationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
