/*
 * Dispute webhooks
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.disputewebhooks;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.Arrays;
import java.util.logging.Logger;

/** DisputeNotificationRequest */
@JsonPropertyOrder({
  DisputeNotificationRequest.JSON_PROPERTY_DATA,
  DisputeNotificationRequest.JSON_PROPERTY_TYPE
})
public class DisputeNotificationRequest {
  public static final String JSON_PROPERTY_DATA = "data";
  private DisputeEventNotification data;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetData = false;

  /** Type of webhook. */
  public enum TypeEnum {
    BALANCEPLATFORM_DISPUTE_CREATED(String.valueOf("balancePlatform.dispute.created")),

    BALANCEPLATFORM_DISPUTE_UPDATED(String.valueOf("balancePlatform.dispute.updated"));

    private static final Logger LOG = Logger.getLogger(TypeEnum.class.getName());

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      // handling unexpected value
      LOG.warning(
          "TypeEnum: unexpected enum value '"
              + value
              + "' - Supported values are "
              + Arrays.toString(TypeEnum.values()));
      return null;
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetType = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public DisputeNotificationRequest() {}

  /**
   * data
   *
   * @param data
   * @return the current {@code DisputeNotificationRequest} instance, allowing for method chaining
   */
  public DisputeNotificationRequest data(DisputeEventNotification data) {
    this.data = data;
    isSetData = true; // mark as set
    return this;
  }

  /**
   * Get data
   *
   * @return data
   */
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DisputeEventNotification getData() {
    return data;
  }

  /**
   * data
   *
   * @param data
   */
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(DisputeEventNotification data) {
    this.data = data;
    isSetData = true; // mark as set
  }

  /**
   * Type of webhook.
   *
   * @param type Type of webhook.
   * @return the current {@code DisputeNotificationRequest} instance, allowing for method chaining
   */
  public DisputeNotificationRequest type(TypeEnum type) {
    this.type = type;
    isSetType = true; // mark as set
    return this;
  }

  /**
   * Type of webhook.
   *
   * @return type Type of webhook.
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }

  /**
   * Type of webhook.
   *
   * @param type Type of webhook.
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
    isSetType = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public DisputeNotificationRequest includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this DisputeNotificationRequest object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisputeNotificationRequest disputeNotificationRequest = (DisputeNotificationRequest) o;
    return Objects.equals(this.data, disputeNotificationRequest.data)
        && Objects.equals(this.type, disputeNotificationRequest.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisputeNotificationRequest {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetData) {
      addIfNull(nulls, JSON_PROPERTY_DATA, this.data);
    }
    if (isSetType) {
      addIfNull(nulls, JSON_PROPERTY_TYPE, this.type);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of DisputeNotificationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DisputeNotificationRequest
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     DisputeNotificationRequest
   */
  public static DisputeNotificationRequest fromJson(String jsonString)
      throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, DisputeNotificationRequest.class);
  }

  /**
   * Convert an instance of DisputeNotificationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
