/*
 * Configuration API
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.balanceplatform;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import java.util.*;
import java.util.logging.Logger;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * NZLocalAccountIdentification
 */
@JsonPropertyOrder({
  NZLocalAccountIdentification.JSON_PROPERTY_ACCOUNT_NUMBER,
  NZLocalAccountIdentification.JSON_PROPERTY_TYPE
})

public class NZLocalAccountIdentification {
  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "accountNumber";
  private String accountNumber;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetAccountNumber = false;

    /**
   * **nzLocal**
   */
  public enum TypeEnum {

    NZLOCAL(String.valueOf("nzLocal"));

    private static final Logger LOG = Logger.getLogger(TypeEnum.class.getName());

    private String value;

    TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      // handling unexpected value
      LOG.warning("TypeEnum: unexpected enum value '" + value + "' - Supported values are "+ Arrays.toString(TypeEnum.values()));
      return null;
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetType = false;

   
  /** Sets whether attributes with null values should be explicitly included in the JSON payload. Default is false. */
  @JsonIgnore
  private boolean includeNullValues = false;

  public NZLocalAccountIdentification() { 
  }

  /**
   * The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   *
   * @param accountNumber The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   * @return the current {@code NZLocalAccountIdentification} instance, allowing for method chaining
   */
  public NZLocalAccountIdentification accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    isSetAccountNumber = true; // mark as set
    return this;
  }

  /**
   * The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   * @return accountNumber The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccountNumber() {
    return accountNumber;
  }

  /**
   * The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   *
   * @param accountNumber The 15-16 digit bank account number. The first 2 digits are the bank number, the next 4 digits are the branch number, the next 7 digits are the account number, and the final 2-3 digits are the suffix.
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    isSetAccountNumber = true; // mark as set
  }
  
  /**
   * **nzLocal**
   *
   * @param type **nzLocal**
   * @return the current {@code NZLocalAccountIdentification} instance, allowing for method chaining
   */
  public NZLocalAccountIdentification type(TypeEnum type) {
    this.type = type;
    isSetType = true; // mark as set
    return this;
  }

  /**
   * **nzLocal**
   * @return type **nzLocal**
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }

  /**
   * **nzLocal**
   *
   * @param type **nzLocal**
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
    isSetType = true; // mark as set
  }
  

  /** Configures whether null values are explicitly serialized in the JSON payload. Default is false. */
  public NZLocalAccountIdentification includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /** Sets whether null values should be explicitly serialized in the JSON payload. Default is false. */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }


  /**
   * Return true if this NZLocalAccountIdentification object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NZLocalAccountIdentification nzLocalAccountIdentification = (NZLocalAccountIdentification) o;
    return Objects.equals(this.accountNumber, nzLocalAccountIdentification.accountNumber) &&
        Objects.equals(this.isSetAccountNumber, nzLocalAccountIdentification.isSetAccountNumber) &&
        Objects.equals(this.type, nzLocalAccountIdentification.type) &&
        Objects.equals(this.isSetType, nzLocalAccountIdentification.isSetType)
    ;
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, isSetAccountNumber, type, isSetType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NZLocalAccountIdentification {\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetAccountNumber) {
      addIfNull(nulls, JSON_PROPERTY_ACCOUNT_NUMBER, this.accountNumber);
    }
    if (isSetType) {
      addIfNull(nulls, JSON_PROPERTY_TYPE, this.type);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

/**
   * Create an instance of NZLocalAccountIdentification given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NZLocalAccountIdentification
   * @throws JsonProcessingException if the JSON string is invalid with respect to NZLocalAccountIdentification
   */
  public static NZLocalAccountIdentification fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, NZLocalAccountIdentification.class);
  }
/**
  * Convert an instance of NZLocalAccountIdentification to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
