/*
 * Management API
 *
 * The version of the OpenAPI document: 3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.management;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.ArrayList;
import java.util.List;

/** CreateMerchantUserRequest */
@JsonPropertyOrder({
  CreateMerchantUserRequest.JSON_PROPERTY_ACCOUNT_GROUPS,
  CreateMerchantUserRequest.JSON_PROPERTY_EMAIL,
  CreateMerchantUserRequest.JSON_PROPERTY_LOGIN_METHOD,
  CreateMerchantUserRequest.JSON_PROPERTY_NAME,
  CreateMerchantUserRequest.JSON_PROPERTY_ROLES,
  CreateMerchantUserRequest.JSON_PROPERTY_TIME_ZONE_CODE,
  CreateMerchantUserRequest.JSON_PROPERTY_USERNAME
})
public class CreateMerchantUserRequest {
  public static final String JSON_PROPERTY_ACCOUNT_GROUPS = "accountGroups";
  private List<String> accountGroups;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetAccountGroups = false;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetEmail = false;

  public static final String JSON_PROPERTY_LOGIN_METHOD = "loginMethod";
  private String loginMethod;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetLoginMethod = false;

  public static final String JSON_PROPERTY_NAME = "name";
  private Name name;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetName = false;

  public static final String JSON_PROPERTY_ROLES = "roles";
  private List<String> roles;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetRoles = false;

  public static final String JSON_PROPERTY_TIME_ZONE_CODE = "timeZoneCode";
  private String timeZoneCode;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetTimeZoneCode = false;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetUsername = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public CreateMerchantUserRequest() {}

  /**
   * The list of [account groups](https://docs.adyen.com/account/account-structure#account-groups)
   * associated with this user.
   *
   * @param accountGroups The list of [account
   *     groups](https://docs.adyen.com/account/account-structure#account-groups) associated with
   *     this user.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest accountGroups(List<String> accountGroups) {
    this.accountGroups = accountGroups;
    isSetAccountGroups = true; // mark as set
    return this;
  }

  public CreateMerchantUserRequest addAccountGroupsItem(String accountGroupsItem) {
    if (this.accountGroups == null) {
      this.accountGroups = new ArrayList<>();
    }
    this.accountGroups.add(accountGroupsItem);
    return this;
  }

  /**
   * The list of [account groups](https://docs.adyen.com/account/account-structure#account-groups)
   * associated with this user.
   *
   * @return accountGroups The list of [account
   *     groups](https://docs.adyen.com/account/account-structure#account-groups) associated with
   *     this user.
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAccountGroups() {
    return accountGroups;
  }

  /**
   * The list of [account groups](https://docs.adyen.com/account/account-structure#account-groups)
   * associated with this user.
   *
   * @param accountGroups The list of [account
   *     groups](https://docs.adyen.com/account/account-structure#account-groups) associated with
   *     this user.
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountGroups(List<String> accountGroups) {
    this.accountGroups = accountGroups;
    isSetAccountGroups = true; // mark as set
  }

  /**
   * The email address of the user.
   *
   * @param email The email address of the user.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest email(String email) {
    this.email = email;
    isSetEmail = true; // mark as set
    return this;
  }

  /**
   * The email address of the user.
   *
   * @return email The email address of the user.
   */
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }

  /**
   * The email address of the user.
   *
   * @param email The email address of the user.
   */
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
    isSetEmail = true; // mark as set
  }

  /**
   * The requested login method for the user. To use SSO, you must already have SSO configured with
   * Adyen before creating the user. Possible values: **Username &amp; account**, **Email**, or
   * **SSO**
   *
   * @param loginMethod The requested login method for the user. To use SSO, you must already have
   *     SSO configured with Adyen before creating the user. Possible values: **Username &amp;
   *     account**, **Email**, or **SSO**
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest loginMethod(String loginMethod) {
    this.loginMethod = loginMethod;
    isSetLoginMethod = true; // mark as set
    return this;
  }

  /**
   * The requested login method for the user. To use SSO, you must already have SSO configured with
   * Adyen before creating the user. Possible values: **Username &amp; account**, **Email**, or
   * **SSO**
   *
   * @return loginMethod The requested login method for the user. To use SSO, you must already have
   *     SSO configured with Adyen before creating the user. Possible values: **Username &amp;
   *     account**, **Email**, or **SSO**
   */
  @JsonProperty(JSON_PROPERTY_LOGIN_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLoginMethod() {
    return loginMethod;
  }

  /**
   * The requested login method for the user. To use SSO, you must already have SSO configured with
   * Adyen before creating the user. Possible values: **Username &amp; account**, **Email**, or
   * **SSO**
   *
   * @param loginMethod The requested login method for the user. To use SSO, you must already have
   *     SSO configured with Adyen before creating the user. Possible values: **Username &amp;
   *     account**, **Email**, or **SSO**
   */
  @JsonProperty(JSON_PROPERTY_LOGIN_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginMethod(String loginMethod) {
    this.loginMethod = loginMethod;
    isSetLoginMethod = true; // mark as set
  }

  /**
   * The user&#39;s full name. Allowed length: 1—80 characters.
   *
   * @param name The user&#39;s full name. Allowed length: 1—80 characters.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest name(Name name) {
    this.name = name;
    isSetName = true; // mark as set
    return this;
  }

  /**
   * The user&#39;s full name. Allowed length: 1—80 characters.
   *
   * @return name The user&#39;s full name. Allowed length: 1—80 characters.
   */
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Name getName() {
    return name;
  }

  /**
   * The user&#39;s full name. Allowed length: 1—80 characters.
   *
   * @param name The user&#39;s full name. Allowed length: 1—80 characters.
   */
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(Name name) {
    this.name = name;
    isSetName = true; // mark as set
  }

  /**
   * The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   *
   * @param roles The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest roles(List<String> roles) {
    this.roles = roles;
    isSetRoles = true; // mark as set
    return this;
  }

  public CreateMerchantUserRequest addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   *
   * @return roles The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   */
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getRoles() {
    return roles;
  }

  /**
   * The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   *
   * @param roles The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
   */
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoles(List<String> roles) {
    this.roles = roles;
    isSetRoles = true; // mark as set
  }

  /**
   * The [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the
   * time zone of the user. For example, **Europe/Amsterdam**.
   *
   * @param timeZoneCode The [tz database
   *     name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the time zone of the
   *     user. For example, **Europe/Amsterdam**.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest timeZoneCode(String timeZoneCode) {
    this.timeZoneCode = timeZoneCode;
    isSetTimeZoneCode = true; // mark as set
    return this;
  }

  /**
   * The [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the
   * time zone of the user. For example, **Europe/Amsterdam**.
   *
   * @return timeZoneCode The [tz database
   *     name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the time zone of the
   *     user. For example, **Europe/Amsterdam**.
   */
  @JsonProperty(JSON_PROPERTY_TIME_ZONE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimeZoneCode() {
    return timeZoneCode;
  }

  /**
   * The [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the
   * time zone of the user. For example, **Europe/Amsterdam**.
   *
   * @param timeZoneCode The [tz database
   *     name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the time zone of the
   *     user. For example, **Europe/Amsterdam**.
   */
  @JsonProperty(JSON_PROPERTY_TIME_ZONE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeZoneCode(String timeZoneCode) {
    this.timeZoneCode = timeZoneCode;
    isSetTimeZoneCode = true; // mark as set
  }

  /**
   * The user&#39;s email address that will be their username. Must be the same as the one in the
   * &#x60;email&#x60; field.
   *
   * @param username The user&#39;s email address that will be their username. Must be the same as
   *     the one in the &#x60;email&#x60; field.
   * @return the current {@code CreateMerchantUserRequest} instance, allowing for method chaining
   */
  public CreateMerchantUserRequest username(String username) {
    this.username = username;
    isSetUsername = true; // mark as set
    return this;
  }

  /**
   * The user&#39;s email address that will be their username. Must be the same as the one in the
   * &#x60;email&#x60; field.
   *
   * @return username The user&#39;s email address that will be their username. Must be the same as
   *     the one in the &#x60;email&#x60; field.
   */
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUsername() {
    return username;
  }

  /**
   * The user&#39;s email address that will be their username. Must be the same as the one in the
   * &#x60;email&#x60; field.
   *
   * @param username The user&#39;s email address that will be their username. Must be the same as
   *     the one in the &#x60;email&#x60; field.
   */
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(String username) {
    this.username = username;
    isSetUsername = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public CreateMerchantUserRequest includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this CreateMerchantUserRequest object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMerchantUserRequest createMerchantUserRequest = (CreateMerchantUserRequest) o;
    return Objects.equals(this.accountGroups, createMerchantUserRequest.accountGroups)
        && Objects.equals(this.email, createMerchantUserRequest.email)
        && Objects.equals(this.loginMethod, createMerchantUserRequest.loginMethod)
        && Objects.equals(this.name, createMerchantUserRequest.name)
        && Objects.equals(this.roles, createMerchantUserRequest.roles)
        && Objects.equals(this.timeZoneCode, createMerchantUserRequest.timeZoneCode)
        && Objects.equals(this.username, createMerchantUserRequest.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountGroups, email, loginMethod, name, roles, timeZoneCode, username);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMerchantUserRequest {\n");
    sb.append("    accountGroups: ").append(toIndentedString(accountGroups)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    loginMethod: ").append(toIndentedString(loginMethod)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    timeZoneCode: ").append(toIndentedString(timeZoneCode)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetAccountGroups) {
      addIfNull(nulls, JSON_PROPERTY_ACCOUNT_GROUPS, this.accountGroups);
    }
    if (isSetEmail) {
      addIfNull(nulls, JSON_PROPERTY_EMAIL, this.email);
    }
    if (isSetLoginMethod) {
      addIfNull(nulls, JSON_PROPERTY_LOGIN_METHOD, this.loginMethod);
    }
    if (isSetName) {
      addIfNull(nulls, JSON_PROPERTY_NAME, this.name);
    }
    if (isSetRoles) {
      addIfNull(nulls, JSON_PROPERTY_ROLES, this.roles);
    }
    if (isSetTimeZoneCode) {
      addIfNull(nulls, JSON_PROPERTY_TIME_ZONE_CODE, this.timeZoneCode);
    }
    if (isSetUsername) {
      addIfNull(nulls, JSON_PROPERTY_USERNAME, this.username);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of CreateMerchantUserRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateMerchantUserRequest
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     CreateMerchantUserRequest
   */
  public static CreateMerchantUserRequest fromJson(String jsonString)
      throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, CreateMerchantUserRequest.class);
  }

  /**
   * Convert an instance of CreateMerchantUserRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
