/*
 * Management API
 *
 * The version of the OpenAPI document: 3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.management;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.ArrayList;
import java.util.List;

/** ListCompanyResponse */
@JsonPropertyOrder({
  ListCompanyResponse.JSON_PROPERTY_LINKS,
  ListCompanyResponse.JSON_PROPERTY_DATA,
  ListCompanyResponse.JSON_PROPERTY_ITEMS_TOTAL,
  ListCompanyResponse.JSON_PROPERTY_PAGES_TOTAL
})
public class ListCompanyResponse {
  public static final String JSON_PROPERTY_LINKS = "_links";
  private PaginationLinks links;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetLinks = false;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<Company> data;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetData = false;

  public static final String JSON_PROPERTY_ITEMS_TOTAL = "itemsTotal";
  private Integer itemsTotal;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetItemsTotal = false;

  public static final String JSON_PROPERTY_PAGES_TOTAL = "pagesTotal";
  private Integer pagesTotal;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPagesTotal = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public ListCompanyResponse() {}

  /**
   * Pagination references.
   *
   * @param links Pagination references.
   * @return the current {@code ListCompanyResponse} instance, allowing for method chaining
   */
  public ListCompanyResponse links(PaginationLinks links) {
    this.links = links;
    isSetLinks = true; // mark as set
    return this;
  }

  /**
   * Pagination references.
   *
   * @return links Pagination references.
   */
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaginationLinks getLinks() {
    return links;
  }

  /**
   * Pagination references.
   *
   * @param links Pagination references.
   */
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(PaginationLinks links) {
    this.links = links;
    isSetLinks = true; // mark as set
  }

  /**
   * The list of companies.
   *
   * @param data The list of companies.
   * @return the current {@code ListCompanyResponse} instance, allowing for method chaining
   */
  public ListCompanyResponse data(List<Company> data) {
    this.data = data;
    isSetData = true; // mark as set
    return this;
  }

  public ListCompanyResponse addDataItem(Company dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * The list of companies.
   *
   * @return data The list of companies.
   */
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Company> getData() {
    return data;
  }

  /**
   * The list of companies.
   *
   * @param data The list of companies.
   */
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(List<Company> data) {
    this.data = data;
    isSetData = true; // mark as set
  }

  /**
   * Total number of items.
   *
   * @param itemsTotal Total number of items.
   * @return the current {@code ListCompanyResponse} instance, allowing for method chaining
   */
  public ListCompanyResponse itemsTotal(Integer itemsTotal) {
    this.itemsTotal = itemsTotal;
    isSetItemsTotal = true; // mark as set
    return this;
  }

  /**
   * Total number of items.
   *
   * @return itemsTotal Total number of items.
   */
  @JsonProperty(JSON_PROPERTY_ITEMS_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getItemsTotal() {
    return itemsTotal;
  }

  /**
   * Total number of items.
   *
   * @param itemsTotal Total number of items.
   */
  @JsonProperty(JSON_PROPERTY_ITEMS_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItemsTotal(Integer itemsTotal) {
    this.itemsTotal = itemsTotal;
    isSetItemsTotal = true; // mark as set
  }

  /**
   * Total number of pages.
   *
   * @param pagesTotal Total number of pages.
   * @return the current {@code ListCompanyResponse} instance, allowing for method chaining
   */
  public ListCompanyResponse pagesTotal(Integer pagesTotal) {
    this.pagesTotal = pagesTotal;
    isSetPagesTotal = true; // mark as set
    return this;
  }

  /**
   * Total number of pages.
   *
   * @return pagesTotal Total number of pages.
   */
  @JsonProperty(JSON_PROPERTY_PAGES_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPagesTotal() {
    return pagesTotal;
  }

  /**
   * Total number of pages.
   *
   * @param pagesTotal Total number of pages.
   */
  @JsonProperty(JSON_PROPERTY_PAGES_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagesTotal(Integer pagesTotal) {
    this.pagesTotal = pagesTotal;
    isSetPagesTotal = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public ListCompanyResponse includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this ListCompanyResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCompanyResponse listCompanyResponse = (ListCompanyResponse) o;
    return Objects.equals(this.links, listCompanyResponse.links)
        && Objects.equals(this.data, listCompanyResponse.data)
        && Objects.equals(this.itemsTotal, listCompanyResponse.itemsTotal)
        && Objects.equals(this.pagesTotal, listCompanyResponse.pagesTotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, data, itemsTotal, pagesTotal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCompanyResponse {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    itemsTotal: ").append(toIndentedString(itemsTotal)).append("\n");
    sb.append("    pagesTotal: ").append(toIndentedString(pagesTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetLinks) {
      addIfNull(nulls, JSON_PROPERTY_LINKS, this.links);
    }
    if (isSetData) {
      addIfNull(nulls, JSON_PROPERTY_DATA, this.data);
    }
    if (isSetItemsTotal) {
      addIfNull(nulls, JSON_PROPERTY_ITEMS_TOTAL, this.itemsTotal);
    }
    if (isSetPagesTotal) {
      addIfNull(nulls, JSON_PROPERTY_PAGES_TOTAL, this.pagesTotal);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of ListCompanyResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListCompanyResponse
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     ListCompanyResponse
   */
  public static ListCompanyResponse fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, ListCompanyResponse.class);
  }

  /**
   * Convert an instance of ListCompanyResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
