/*
 * Management API
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.management;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import java.util.*;
import java.util.logging.Logger;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * SvsInfo
 */
@JsonPropertyOrder({
  SvsInfo.JSON_PROPERTY_AUTHORISATION_MID,
  SvsInfo.JSON_PROPERTY_CURRENCY_CODE
})

public class SvsInfo {
  public static final String JSON_PROPERTY_AUTHORISATION_MID = "authorisationMid";
  private String authorisationMid;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetAuthorisationMid = false;

    public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private String currencyCode;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetCurrencyCode = false;

   
  /** Sets whether attributes with null values should be explicitly included in the JSON payload. Default is false. */
  @JsonIgnore
  private boolean includeNullValues = false;

  public SvsInfo() { 
  }

  /**
   * The merchant ID (MID) that the acquirer recognizes you by.
   *
   * @param authorisationMid The merchant ID (MID) that the acquirer recognizes you by.
   * @return the current {@code SvsInfo} instance, allowing for method chaining
   */
  public SvsInfo authorisationMid(String authorisationMid) {
    this.authorisationMid = authorisationMid;
    isSetAuthorisationMid = true; // mark as set
    return this;
  }

  /**
   * The merchant ID (MID) that the acquirer recognizes you by.
   * @return authorisationMid The merchant ID (MID) that the acquirer recognizes you by.
   */
  @JsonProperty(JSON_PROPERTY_AUTHORISATION_MID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAuthorisationMid() {
    return authorisationMid;
  }

  /**
   * The merchant ID (MID) that the acquirer recognizes you by.
   *
   * @param authorisationMid The merchant ID (MID) that the acquirer recognizes you by.
   */
  @JsonProperty(JSON_PROPERTY_AUTHORISATION_MID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorisationMid(String authorisationMid) {
    this.authorisationMid = authorisationMid;
    isSetAuthorisationMid = true; // mark as set
  }
  
  /**
   * The three-character ISO currency code, example **USD**
   *
   * @param currencyCode The three-character ISO currency code, example **USD**
   * @return the current {@code SvsInfo} instance, allowing for method chaining
   */
  public SvsInfo currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    isSetCurrencyCode = true; // mark as set
    return this;
  }

  /**
   * The three-character ISO currency code, example **USD**
   * @return currencyCode The three-character ISO currency code, example **USD**
   */
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrencyCode() {
    return currencyCode;
  }

  /**
   * The three-character ISO currency code, example **USD**
   *
   * @param currencyCode The three-character ISO currency code, example **USD**
   */
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    isSetCurrencyCode = true; // mark as set
  }
  

  /** Configures whether null values are explicitly serialized in the JSON payload. Default is false. */
  public SvsInfo includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /** Sets whether null values should be explicitly serialized in the JSON payload. Default is false. */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }


  /**
   * Return true if this SvsInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SvsInfo svsInfo = (SvsInfo) o;
    return Objects.equals(this.authorisationMid, svsInfo.authorisationMid) &&
        Objects.equals(this.isSetAuthorisationMid, svsInfo.isSetAuthorisationMid) &&
        Objects.equals(this.currencyCode, svsInfo.currencyCode) &&
        Objects.equals(this.isSetCurrencyCode, svsInfo.isSetCurrencyCode)
    ;
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorisationMid, isSetAuthorisationMid, currencyCode, isSetCurrencyCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SvsInfo {\n");
    sb.append("    authorisationMid: ").append(toIndentedString(authorisationMid)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetAuthorisationMid) {
      addIfNull(nulls, JSON_PROPERTY_AUTHORISATION_MID, this.authorisationMid);
    }
    if (isSetCurrencyCode) {
      addIfNull(nulls, JSON_PROPERTY_CURRENCY_CODE, this.currencyCode);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

/**
   * Create an instance of SvsInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SvsInfo
   * @throws JsonProcessingException if the JSON string is invalid with respect to SvsInfo
   */
  public static SvsInfo fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, SvsInfo.class);
  }
/**
  * Convert an instance of SvsInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
