package com.adyen.model.clouddevice;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Arrays;

/** Type of POI capabilities. */
public enum POICapabilitiesType {

  /**
   * Used by the Sale System when the device is managed by the POI Terminal, to ask question or
   * display some information to the Cashier.
   */
  @Schema(
      description =
          "Used by the Sale System when the device is managed by the POI Terminal, to ask question or display some information to the Cashier.")
  CASHIER_DISPLAY("CashierDisplay"),

  /**
   * To display to the Cashier information is related to an error situation occurring on the Sale
   * Terminal when the device is managed by the POI Terminal.
   */
  @Schema(
      description =
          "To display to the Cashier information is related to an error situation occurring on the Sale Terminal when the device is managed by the POI Terminal.")
  CASHIER_ERROR("CashierError"),

  /**
   * Any kind of keyboard allowing all or part of the commands of the Input messageType request from
   * the POI System to the Sale System (InputCommand data element). The
   */
  @Schema(
      description =
          "Any kind of keyboard allowing all or part of the commands of the Input message request from the POI System to the Sale System (InputCommand data element). The")
  CASHIER_INPUT("CashierInput"),

  /**
   * Standard Customer display interface used by the Sale System to ask question, or to show
   * information to the Customer outside a Service dialogue.
   */
  @Schema(
      description =
          "Standard Customer display interface used by the Sale System to ask question, or to show information to the Customer outside a Service dialogue.")
  CUSTOMER_DISPLAY("CustomerDisplay"),

  /**
   * To display to the Customer information is related to an error situation occurring on the Sale
   * Terminal during a Sale transaction.
   */
  @Schema(
      description =
          "To display to the Customer information is related to an error situation occurring on the Sale Terminal during a Sale transaction.")
  CUSTOMER_ERROR("CustomerError"),

  /**
   * Any kind of keyboard allowing all or part of the commands of the Input messageType request from
   * the POI System to the Sale System (InputCommand data element). The
   */
  @Schema(
      description =
          "Any kind of keyboard allowing all or part of the commands of the Input message request from the POI System to the Sale System (InputCommand data element). The")
  CUSTOMER_INPUT("CustomerInput"),

  /** Printer for the Sale receipt. */
  @Schema(description = "Printer for the Sale receipt.")
  PRINTER_RECEIPT("PrinterReceipt"),

  /**
   * When the Sale System wants to print specific document (check, dynamic currency conversion ...).
   */
  @Schema(
      description =
          "When the Sale System wants to print specific document (check, dynamic currency conversion ...). ")
  PRINTER_DOCUMENT("PrinterDocument"),

  /** Coupons, voucher or special ticket generated by the Sale System and to be printed. */
  @Schema(
      description =
          "Coupons, voucher or special ticket generated by the Sale System and to be printed.")
  PRINTER_VOUCHER("PrinterVoucher"),

  /** Magnetic stripe card reader */
  @Schema(description = "Magnetic stripe card reader")
  MAG_STRIPE("MagStripe"),

  /** Contact ICC card reader */
  ICC("ICC"),

  /** Contactless card reader with EMV applications */
  @Schema(description = "Contactless card reader with EMV applications")
  EMV_CONTACTLESS("EMVContactless"),

  /** Device which performs cash change, cash dispense or cash acceptance. */
  @Schema(description = "Device which performs cash change, cash dispense or cash acceptance.")
  CASH_HANDLING("CashHandling");

  private final String value;

  POICapabilitiesType(String v) {
    value = v;
  }

  /**
   * Returns the string representation of the POICapabilitiesType.
   *
   * @return the string value
   */
  @JsonValue
  public String value() {
    return value;
  }

  /**
   * Creates a POICapabilitiesType from a string value.
   *
   * @param v the string value
   * @return the corresponding POICapabilitiesType
   */
  @JsonCreator
  public static POICapabilitiesType fromValue(String v) {
    return Arrays.stream(values()).filter(s -> s.value.equals(v)).findFirst().orElse(null);
  }
}
