/*
 * POS Mobile API
 *
 * The version of the OpenAPI document: 68
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.posmobile;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;

/** CreateSessionResponse */
@JsonPropertyOrder({
  CreateSessionResponse.JSON_PROPERTY_ID,
  CreateSessionResponse.JSON_PROPERTY_INSTALLATION_ID,
  CreateSessionResponse.JSON_PROPERTY_MERCHANT_ACCOUNT,
  CreateSessionResponse.JSON_PROPERTY_SDK_DATA,
  CreateSessionResponse.JSON_PROPERTY_STORE
})
public class CreateSessionResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetId = false;

  public static final String JSON_PROPERTY_INSTALLATION_ID = "installationId";
  private String installationId;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetInstallationId = false;

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT = "merchantAccount";
  private String merchantAccount;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetMerchantAccount = false;

  public static final String JSON_PROPERTY_SDK_DATA = "sdkData";
  private String sdkData;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetSdkData = false;

  public static final String JSON_PROPERTY_STORE = "store";
  private String store;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetStore = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public CreateSessionResponse() {}

  /**
   * The unique identifier of the session.
   *
   * @param id The unique identifier of the session.
   * @return the current {@code CreateSessionResponse} instance, allowing for method chaining
   */
  public CreateSessionResponse id(String id) {
    this.id = id;
    isSetId = true; // mark as set
    return this;
  }

  /**
   * The unique identifier of the session.
   *
   * @return id The unique identifier of the session.
   */
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }

  /**
   * The unique identifier of the session.
   *
   * @param id The unique identifier of the session.
   */
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
    isSetId = true; // mark as set
  }

  /**
   * The unique identifier of the SDK installation. If you create the [Terminal
   * API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/) transaction
   * request on your backend, use this as the &#x60;POIID&#x60; in the &#x60;MessageHeader&#x60; of
   * the request.
   *
   * @param installationId The unique identifier of the SDK installation. If you create the
   *     [Terminal API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/)
   *     transaction request on your backend, use this as the &#x60;POIID&#x60; in the
   *     &#x60;MessageHeader&#x60; of the request.
   * @return the current {@code CreateSessionResponse} instance, allowing for method chaining
   */
  public CreateSessionResponse installationId(String installationId) {
    this.installationId = installationId;
    isSetInstallationId = true; // mark as set
    return this;
  }

  /**
   * The unique identifier of the SDK installation. If you create the [Terminal
   * API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/) transaction
   * request on your backend, use this as the &#x60;POIID&#x60; in the &#x60;MessageHeader&#x60; of
   * the request.
   *
   * @return installationId The unique identifier of the SDK installation. If you create the
   *     [Terminal API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/)
   *     transaction request on your backend, use this as the &#x60;POIID&#x60; in the
   *     &#x60;MessageHeader&#x60; of the request.
   */
  @JsonProperty(JSON_PROPERTY_INSTALLATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInstallationId() {
    return installationId;
  }

  /**
   * The unique identifier of the SDK installation. If you create the [Terminal
   * API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/) transaction
   * request on your backend, use this as the &#x60;POIID&#x60; in the &#x60;MessageHeader&#x60; of
   * the request.
   *
   * @param installationId The unique identifier of the SDK installation. If you create the
   *     [Terminal API](https://docs.adyen.com/point-of-sale/design-your-integration/terminal-api/)
   *     transaction request on your backend, use this as the &#x60;POIID&#x60; in the
   *     &#x60;MessageHeader&#x60; of the request.
   */
  @JsonProperty(JSON_PROPERTY_INSTALLATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstallationId(String installationId) {
    this.installationId = installationId;
    isSetInstallationId = true; // mark as set
  }

  /**
   * The unique identifier of your merchant account.
   *
   * @param merchantAccount The unique identifier of your merchant account.
   * @return the current {@code CreateSessionResponse} instance, allowing for method chaining
   */
  public CreateSessionResponse merchantAccount(String merchantAccount) {
    this.merchantAccount = merchantAccount;
    isSetMerchantAccount = true; // mark as set
    return this;
  }

  /**
   * The unique identifier of your merchant account.
   *
   * @return merchantAccount The unique identifier of your merchant account.
   */
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantAccount() {
    return merchantAccount;
  }

  /**
   * The unique identifier of your merchant account.
   *
   * @param merchantAccount The unique identifier of your merchant account.
   */
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccount(String merchantAccount) {
    this.merchantAccount = merchantAccount;
    isSetMerchantAccount = true; // mark as set
  }

  /**
   * The data that the SDK uses to authenticate responses from the Adyen payments platform. Pass
   * this value to your POS app.
   *
   * @param sdkData The data that the SDK uses to authenticate responses from the Adyen payments
   *     platform. Pass this value to your POS app.
   * @return the current {@code CreateSessionResponse} instance, allowing for method chaining
   */
  public CreateSessionResponse sdkData(String sdkData) {
    this.sdkData = sdkData;
    isSetSdkData = true; // mark as set
    return this;
  }

  /**
   * The data that the SDK uses to authenticate responses from the Adyen payments platform. Pass
   * this value to your POS app.
   *
   * @return sdkData The data that the SDK uses to authenticate responses from the Adyen payments
   *     platform. Pass this value to your POS app.
   */
  @JsonProperty(JSON_PROPERTY_SDK_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSdkData() {
    return sdkData;
  }

  /**
   * The data that the SDK uses to authenticate responses from the Adyen payments platform. Pass
   * this value to your POS app.
   *
   * @param sdkData The data that the SDK uses to authenticate responses from the Adyen payments
   *     platform. Pass this value to your POS app.
   */
  @JsonProperty(JSON_PROPERTY_SDK_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSdkData(String sdkData) {
    this.sdkData = sdkData;
    isSetSdkData = true; // mark as set
  }

  /**
   * The unique identifier of the store that you want to process transactions for.
   *
   * @param store The unique identifier of the store that you want to process transactions for.
   * @return the current {@code CreateSessionResponse} instance, allowing for method chaining
   */
  public CreateSessionResponse store(String store) {
    this.store = store;
    isSetStore = true; // mark as set
    return this;
  }

  /**
   * The unique identifier of the store that you want to process transactions for.
   *
   * @return store The unique identifier of the store that you want to process transactions for.
   */
  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStore() {
    return store;
  }

  /**
   * The unique identifier of the store that you want to process transactions for.
   *
   * @param store The unique identifier of the store that you want to process transactions for.
   */
  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStore(String store) {
    this.store = store;
    isSetStore = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public CreateSessionResponse includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this CreateSessionResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSessionResponse createSessionResponse = (CreateSessionResponse) o;
    return Objects.equals(this.id, createSessionResponse.id)
        && Objects.equals(this.isSetId, createSessionResponse.isSetId)
        && Objects.equals(this.installationId, createSessionResponse.installationId)
        && Objects.equals(this.isSetInstallationId, createSessionResponse.isSetInstallationId)
        && Objects.equals(this.merchantAccount, createSessionResponse.merchantAccount)
        && Objects.equals(this.isSetMerchantAccount, createSessionResponse.isSetMerchantAccount)
        && Objects.equals(this.sdkData, createSessionResponse.sdkData)
        && Objects.equals(this.isSetSdkData, createSessionResponse.isSetSdkData)
        && Objects.equals(this.store, createSessionResponse.store)
        && Objects.equals(this.isSetStore, createSessionResponse.isSetStore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        isSetId,
        installationId,
        isSetInstallationId,
        merchantAccount,
        isSetMerchantAccount,
        sdkData,
        isSetSdkData,
        store,
        isSetStore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSessionResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    installationId: ").append(toIndentedString(installationId)).append("\n");
    sb.append("    merchantAccount: ").append(toIndentedString(merchantAccount)).append("\n");
    sb.append("    sdkData: ").append(toIndentedString(sdkData)).append("\n");
    sb.append("    store: ").append(toIndentedString(store)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetId) {
      addIfNull(nulls, JSON_PROPERTY_ID, this.id);
    }
    if (isSetInstallationId) {
      addIfNull(nulls, JSON_PROPERTY_INSTALLATION_ID, this.installationId);
    }
    if (isSetMerchantAccount) {
      addIfNull(nulls, JSON_PROPERTY_MERCHANT_ACCOUNT, this.merchantAccount);
    }
    if (isSetSdkData) {
      addIfNull(nulls, JSON_PROPERTY_SDK_DATA, this.sdkData);
    }
    if (isSetStore) {
      addIfNull(nulls, JSON_PROPERTY_STORE, this.store);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of CreateSessionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateSessionResponse
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     CreateSessionResponse
   */
  public static CreateSessionResponse fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, CreateSessionResponse.class);
  }

  /**
   * Convert an instance of CreateSessionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
