/*
 * Adyen Terminal API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.tapi;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.*;
import java.util.logging.Logger;

/**
 * Possible values: * **Status** * **Error** * **Display** * **Sound** * **Input** *
 * **POIReplication** * **CustomerAssistance** * **Receipt** * **Document** * **Voucher**
 */
public enum InfoQualify {
  STATUS("Status"),

  ERROR("Error"),

  DISPLAY("Display"),

  SOUND("Sound"),

  INPUT("Input"),

  POI_REPLICATION("POIReplication"),

  CUSTOMER_ASSISTANCE("CustomerAssistance"),

  RECEIPT("Receipt"),

  DOCUMENT("Document"),

  VOUCHER("Voucher");

  private static final Logger LOG = Logger.getLogger(InfoQualify.class.getName());

  private String value;

  InfoQualify(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static InfoQualify fromValue(String value) {
    for (InfoQualify b : InfoQualify.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    // handling unexpected value
    LOG.warning(
        "InfoQualify: unexpected enum value '"
            + value
            + "' - Supported values are "
            + Arrays.toString(InfoQualify.values()));
    return null;
  }
}
