/*
 * Adyen Terminal API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.tapi;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Request sent to terminal to initiate payment. It conveys Information related to the Payment
 * transaction to process. Content of the &#x60;PaymentRequest&#x60; message.
 */
@JsonPropertyOrder({
  PaymentRequest.JSON_PROPERTY_SALE_DATA,
  PaymentRequest.JSON_PROPERTY_PAYMENT_TRANSACTION,
  PaymentRequest.JSON_PROPERTY_PAYMENT_DATA,
  PaymentRequest.JSON_PROPERTY_LOYALTY_DATA
})
public class PaymentRequest {
  public static final String JSON_PROPERTY_SALE_DATA = "SaleData";
  private SaleData saleData;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetSaleData = false;

  public static final String JSON_PROPERTY_PAYMENT_TRANSACTION = "PaymentTransaction";
  private PaymentTransaction paymentTransaction;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPaymentTransaction = false;

  public static final String JSON_PROPERTY_PAYMENT_DATA = "PaymentData";
  private PaymentData paymentData;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPaymentData = false;

  public static final String JSON_PROPERTY_LOYALTY_DATA = "LoyaltyData";
  private List<LoyaltyData> loyaltyData;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetLoyaltyData = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public PaymentRequest() {}

  /**
   * saleData
   *
   * @param saleData
   * @return the current {@code PaymentRequest} instance, allowing for method chaining
   */
  public PaymentRequest saleData(SaleData saleData) {
    this.saleData = saleData;
    isSetSaleData = true; // mark as set
    return this;
  }

  /**
   * Get saleData
   *
   * @return saleData
   */
  @JsonProperty(JSON_PROPERTY_SALE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SaleData getSaleData() {
    return saleData;
  }

  /**
   * saleData
   *
   * @param saleData
   */
  @JsonProperty(JSON_PROPERTY_SALE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaleData(SaleData saleData) {
    this.saleData = saleData;
    isSetSaleData = true; // mark as set
  }

  /**
   * paymentTransaction
   *
   * @param paymentTransaction
   * @return the current {@code PaymentRequest} instance, allowing for method chaining
   */
  public PaymentRequest paymentTransaction(PaymentTransaction paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
    isSetPaymentTransaction = true; // mark as set
    return this;
  }

  /**
   * Get paymentTransaction
   *
   * @return paymentTransaction
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaymentTransaction getPaymentTransaction() {
    return paymentTransaction;
  }

  /**
   * paymentTransaction
   *
   * @param paymentTransaction
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentTransaction(PaymentTransaction paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
    isSetPaymentTransaction = true; // mark as set
  }

  /**
   * paymentData
   *
   * @param paymentData
   * @return the current {@code PaymentRequest} instance, allowing for method chaining
   */
  public PaymentRequest paymentData(PaymentData paymentData) {
    this.paymentData = paymentData;
    isSetPaymentData = true; // mark as set
    return this;
  }

  /**
   * Get paymentData
   *
   * @return paymentData
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PaymentData getPaymentData() {
    return paymentData;
  }

  /**
   * paymentData
   *
   * @param paymentData
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentData(PaymentData paymentData) {
    this.paymentData = paymentData;
    isSetPaymentData = true; // mark as set
  }

  /**
   * Data related to a Loyalty program or account. Loyalty cards used with the payment transaction
   * and read by the Sale System.
   *
   * @param loyaltyData Data related to a Loyalty program or account. Loyalty cards used with the
   *     payment transaction and read by the Sale System.
   * @return the current {@code PaymentRequest} instance, allowing for method chaining
   */
  public PaymentRequest loyaltyData(List<LoyaltyData> loyaltyData) {
    this.loyaltyData = loyaltyData;
    isSetLoyaltyData = true; // mark as set
    return this;
  }

  public PaymentRequest addLoyaltyDataItem(LoyaltyData loyaltyDataItem) {
    if (this.loyaltyData == null) {
      this.loyaltyData = new ArrayList<>();
    }
    this.loyaltyData.add(loyaltyDataItem);
    return this;
  }

  /**
   * Data related to a Loyalty program or account. Loyalty cards used with the payment transaction
   * and read by the Sale System.
   *
   * @return loyaltyData Data related to a Loyalty program or account. Loyalty cards used with the
   *     payment transaction and read by the Sale System.
   */
  @JsonProperty(JSON_PROPERTY_LOYALTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LoyaltyData> getLoyaltyData() {
    return loyaltyData;
  }

  /**
   * Data related to a Loyalty program or account. Loyalty cards used with the payment transaction
   * and read by the Sale System.
   *
   * @param loyaltyData Data related to a Loyalty program or account. Loyalty cards used with the
   *     payment transaction and read by the Sale System.
   */
  @JsonProperty(JSON_PROPERTY_LOYALTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoyaltyData(List<LoyaltyData> loyaltyData) {
    this.loyaltyData = loyaltyData;
    isSetLoyaltyData = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public PaymentRequest includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this PaymentRequest object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return Objects.equals(this.saleData, paymentRequest.saleData)
        && Objects.equals(this.isSetSaleData, paymentRequest.isSetSaleData)
        && Objects.equals(this.paymentTransaction, paymentRequest.paymentTransaction)
        && Objects.equals(this.isSetPaymentTransaction, paymentRequest.isSetPaymentTransaction)
        && Objects.equals(this.paymentData, paymentRequest.paymentData)
        && Objects.equals(this.isSetPaymentData, paymentRequest.isSetPaymentData)
        && Objects.equals(this.loyaltyData, paymentRequest.loyaltyData)
        && Objects.equals(this.isSetLoyaltyData, paymentRequest.isSetLoyaltyData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        saleData,
        isSetSaleData,
        paymentTransaction,
        isSetPaymentTransaction,
        paymentData,
        isSetPaymentData,
        loyaltyData,
        isSetLoyaltyData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    sb.append("    saleData: ").append(toIndentedString(saleData)).append("\n");
    sb.append("    paymentTransaction: ").append(toIndentedString(paymentTransaction)).append("\n");
    sb.append("    paymentData: ").append(toIndentedString(paymentData)).append("\n");
    sb.append("    loyaltyData: ").append(toIndentedString(loyaltyData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetSaleData) {
      addIfNull(nulls, JSON_PROPERTY_SALE_DATA, this.saleData);
    }
    if (isSetPaymentTransaction) {
      addIfNull(nulls, JSON_PROPERTY_PAYMENT_TRANSACTION, this.paymentTransaction);
    }
    if (isSetPaymentData) {
      addIfNull(nulls, JSON_PROPERTY_PAYMENT_DATA, this.paymentData);
    }
    if (isSetLoyaltyData) {
      addIfNull(nulls, JSON_PROPERTY_LOYALTY_DATA, this.loyaltyData);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of PaymentRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentRequest
   * @throws JsonProcessingException if the JSON string is invalid with respect to PaymentRequest
   */
  public static PaymentRequest fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, PaymentRequest.class);
  }

  /**
   * Convert an instance of PaymentRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
