/*
 * Adyen Terminal API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.tapi;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;

/** Point */
@JsonPropertyOrder({Point.JSON_PROPERTY_X, Point.JSON_PROPERTY_Y})
public class Point {
  public static final String JSON_PROPERTY_X = "X";
  private String X;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetX = false;

  public static final String JSON_PROPERTY_Y = "Y";
  private String Y;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetY = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public Point() {}

  /**
   * The hexadecimal value of the coordinates of a point on the abscissa.
   *
   * @param X The hexadecimal value of the coordinates of a point on the abscissa.
   * @return the current {@code Point} instance, allowing for method chaining
   */
  public Point X(String X) {
    this.X = X;
    isSetX = true; // mark as set
    return this;
  }

  /**
   * The hexadecimal value of the coordinates of a point on the abscissa.
   *
   * @return X The hexadecimal value of the coordinates of a point on the abscissa.
   */
  @JsonProperty(JSON_PROPERTY_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getX() {
    return X;
  }

  /**
   * The hexadecimal value of the coordinates of a point on the abscissa.
   *
   * @param X The hexadecimal value of the coordinates of a point on the abscissa.
   */
  @JsonProperty(JSON_PROPERTY_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX(String X) {
    this.X = X;
    isSetX = true; // mark as set
  }

  /**
   * The hexadecimal value of the coordinates of a point on the ordinate.
   *
   * @param Y The hexadecimal value of the coordinates of a point on the ordinate.
   * @return the current {@code Point} instance, allowing for method chaining
   */
  public Point Y(String Y) {
    this.Y = Y;
    isSetY = true; // mark as set
    return this;
  }

  /**
   * The hexadecimal value of the coordinates of a point on the ordinate.
   *
   * @return Y The hexadecimal value of the coordinates of a point on the ordinate.
   */
  @JsonProperty(JSON_PROPERTY_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getY() {
    return Y;
  }

  /**
   * The hexadecimal value of the coordinates of a point on the ordinate.
   *
   * @param Y The hexadecimal value of the coordinates of a point on the ordinate.
   */
  @JsonProperty(JSON_PROPERTY_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setY(String Y) {
    this.Y = Y;
    isSetY = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public Point includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this Point object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Point point = (Point) o;
    return Objects.equals(this.X, point.X)
        && Objects.equals(this.isSetX, point.isSetX)
        && Objects.equals(this.Y, point.Y)
        && Objects.equals(this.isSetY, point.isSetY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(X, isSetX, Y, isSetY);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Point {\n");
    sb.append("    X: ").append(toIndentedString(X)).append("\n");
    sb.append("    Y: ").append(toIndentedString(Y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetX) {
      addIfNull(nulls, JSON_PROPERTY_X, this.X);
    }
    if (isSetY) {
      addIfNull(nulls, JSON_PROPERTY_Y, this.Y);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of Point given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Point
   * @throws JsonProcessingException if the JSON string is invalid with respect to Point
   */
  public static Point fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, Point.class);
  }

  /**
   * Convert an instance of Point to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
