/*
 * Adyen Terminal API
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.terminalmodels;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

/**
 * Identification of the stored value account or the stored value card and the associated product
 * sold by the Sale System for stored value requests.
 */
@JsonPropertyOrder({
  StoredValueAccountID.JSON_PROPERTY_STORED_VALUE_ACCOUNT_TYPE,
  StoredValueAccountID.JSON_PROPERTY_STORED_VALUE_PROVIDER,
  StoredValueAccountID.JSON_PROPERTY_OWNER_NAME,
  StoredValueAccountID.JSON_PROPERTY_EXPIRY_DATE,
  StoredValueAccountID.JSON_PROPERTY_ENTRY_MODE,
  StoredValueAccountID.JSON_PROPERTY_IDENTIFICATION_TYPE,
  StoredValueAccountID.JSON_PROPERTY_STORED_VALUE_I_D
})
public class StoredValueAccountID {
  public static final String JSON_PROPERTY_STORED_VALUE_ACCOUNT_TYPE = "StoredValueAccountType";
  private StoredValueAccountType storedValueAccountType;

  public static final String JSON_PROPERTY_STORED_VALUE_PROVIDER = "StoredValueProvider";
  private String storedValueProvider;

  public static final String JSON_PROPERTY_OWNER_NAME = "OwnerName";
  private String ownerName;

  public static final String JSON_PROPERTY_EXPIRY_DATE = "ExpiryDate";
  private Integer expiryDate;

  /** Gets or Sets entryMode */
  public enum EntryModeEnum {
    CONTACTLESS(String.valueOf("Contactless")),

    FILE(String.valueOf("File")),

    ICC(String.valueOf("ICC")),

    KEYED(String.valueOf("Keyed")),

    MAG_STRIPE(String.valueOf("MagStripe")),

    MANUAL(String.valueOf("Manual")),

    MOBILE(String.valueOf("Mobile")),

    RFID(String.valueOf("RFID")),

    SCANNED(String.valueOf("Scanned")),

    SYNCHRONOUS_ICC(String.valueOf("SynchronousICC")),

    TAPPED(String.valueOf("Tapped"));

    private static final Logger LOG = Logger.getLogger(EntryModeEnum.class.getName());

    private String value;

    EntryModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntryModeEnum fromValue(String value) {
      for (EntryModeEnum b : EntryModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      // handling unexpected value
      LOG.warning(
          "EntryModeEnum: unexpected enum value '"
              + value
              + "' - Supported values are "
              + Arrays.toString(EntryModeEnum.values()));
      return null;
    }
  }

  public static final String JSON_PROPERTY_ENTRY_MODE = "EntryMode";
  private List<EntryModeEnum> entryMode;

  public static final String JSON_PROPERTY_IDENTIFICATION_TYPE = "IdentificationType";
  private IdentificationType identificationType;

  public static final String JSON_PROPERTY_STORED_VALUE_I_D = "StoredValueID";
  private String storedValueID;

  public StoredValueAccountID() {}

  /**
   * Type of stored value account. Allows the distinction of the stored value instrument to access
   * the stored value account. Possible values: * **GiftCard** * **Other** * **PhoneCard**
   *
   * @param storedValueAccountType Type of stored value account. Allows the distinction of the
   *     stored value instrument to access the stored value account. Possible values: * **GiftCard**
   *     * **Other** * **PhoneCard**
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID storedValueAccountType(
      StoredValueAccountType storedValueAccountType) {
    this.storedValueAccountType = storedValueAccountType;
    return this;
  }

  /**
   * Type of stored value account. Allows the distinction of the stored value instrument to access
   * the stored value account. Possible values: * **GiftCard** * **Other** * **PhoneCard**
   *
   * @return storedValueAccountType Type of stored value account. Allows the distinction of the
   *     stored value instrument to access the stored value account. Possible values: * **GiftCard**
   *     * **Other** * **PhoneCard**
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StoredValueAccountType getStoredValueAccountType() {
    return storedValueAccountType;
  }

  /**
   * Type of stored value account. Allows the distinction of the stored value instrument to access
   * the stored value account. Possible values: * **GiftCard** * **Other** * **PhoneCard**
   *
   * @param storedValueAccountType Type of stored value account. Allows the distinction of the
   *     stored value instrument to access the stored value account. Possible values: * **GiftCard**
   *     * **Other** * **PhoneCard**
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoredValueAccountType(StoredValueAccountType storedValueAccountType) {
    this.storedValueAccountType = storedValueAccountType;
  }

  /**
   * Identification of the provider of the stored value account load/reload. When the ProductCode is
   * not sufficient to identify the provider host which delivers the load or reload of the stored
   * value account (for example if it contains the identification of the application.)
   *
   * @param storedValueProvider Identification of the provider of the stored value account
   *     load/reload. When the ProductCode is not sufficient to identify the provider host which
   *     delivers the load or reload of the stored value account (for example if it contains the
   *     identification of the application.)
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID storedValueProvider(String storedValueProvider) {
    this.storedValueProvider = storedValueProvider;
    return this;
  }

  /**
   * Identification of the provider of the stored value account load/reload. When the ProductCode is
   * not sufficient to identify the provider host which delivers the load or reload of the stored
   * value account (for example if it contains the identification of the application.)
   *
   * @return storedValueProvider Identification of the provider of the stored value account
   *     load/reload. When the ProductCode is not sufficient to identify the provider host which
   *     delivers the load or reload of the stored value account (for example if it contains the
   *     identification of the application.)
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStoredValueProvider() {
    return storedValueProvider;
  }

  /**
   * Identification of the provider of the stored value account load/reload. When the ProductCode is
   * not sufficient to identify the provider host which delivers the load or reload of the stored
   * value account (for example if it contains the identification of the application.)
   *
   * @param storedValueProvider Identification of the provider of the stored value account
   *     load/reload. When the ProductCode is not sufficient to identify the provider host which
   *     delivers the load or reload of the stored value account (for example if it contains the
   *     identification of the application.)
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoredValueProvider(String storedValueProvider) {
    this.storedValueProvider = storedValueProvider;
  }

  /**
   * Name of the owner of a stored value account.
   *
   * @param ownerName Name of the owner of a stored value account.
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

  /**
   * Name of the owner of a stored value account.
   *
   * @return ownerName Name of the owner of a stored value account.
   */
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOwnerName() {
    return ownerName;
  }

  /**
   * Name of the owner of a stored value account.
   *
   * @param ownerName Name of the owner of a stored value account.
   */
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }

  /**
   * Date after which the card cannot be used. If EMV expiry date is present, it overrides Track2
   * information. Format is MMYY.
   *
   * @param expiryDate Date after which the card cannot be used. If EMV expiry date is present, it
   *     overrides Track2 information. Format is MMYY.
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID expiryDate(Integer expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * Date after which the card cannot be used. If EMV expiry date is present, it overrides Track2
   * information. Format is MMYY. minimum: 4 maximum: 4
   *
   * @return expiryDate Date after which the card cannot be used. If EMV expiry date is present, it
   *     overrides Track2 information. Format is MMYY.
   */
  @JsonProperty(JSON_PROPERTY_EXPIRY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExpiryDate() {
    return expiryDate;
  }

  /**
   * Date after which the card cannot be used. If EMV expiry date is present, it overrides Track2
   * information. Format is MMYY.
   *
   * @param expiryDate Date after which the card cannot be used. If EMV expiry date is present, it
   *     overrides Track2 information. Format is MMYY.
   */
  @JsonProperty(JSON_PROPERTY_EXPIRY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryDate(Integer expiryDate) {
    this.expiryDate = expiryDate;
  }

  /**
   * entryMode
   *
   * @param entryMode
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID entryMode(List<EntryModeEnum> entryMode) {
    this.entryMode = entryMode;
    return this;
  }

  public StoredValueAccountID addEntryModeItem(EntryModeEnum entryModeItem) {
    if (this.entryMode == null) {
      this.entryMode = new ArrayList<>();
    }
    this.entryMode.add(entryModeItem);
    return this;
  }

  /**
   * Get entryMode
   *
   * @return entryMode
   */
  @JsonProperty(JSON_PROPERTY_ENTRY_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EntryModeEnum> getEntryMode() {
    return entryMode;
  }

  /**
   * entryMode
   *
   * @param entryMode
   */
  @JsonProperty(JSON_PROPERTY_ENTRY_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntryMode(List<EntryModeEnum> entryMode) {
    this.entryMode = entryMode;
  }

  /**
   * Type of account identification. In a request message, it informs the POI System the type of the
   * account or card identification, when provided by the Sale Terminal. (e.g. because the card
   * information is a barcode read by the Cashier on a scanner device). In a response message, it
   * informs the Sale System the type of the account or card identification. Possible values: *
   * **AccountNumber** * **BarCode** * **ISOTrack2** * **PAN** * **PhoneNumber**
   *
   * @param identificationType Type of account identification. In a request message, it informs the
   *     POI System the type of the account or card identification, when provided by the Sale
   *     Terminal. (e.g. because the card information is a barcode read by the Cashier on a scanner
   *     device). In a response message, it informs the Sale System the type of the account or card
   *     identification. Possible values: * **AccountNumber** * **BarCode** * **ISOTrack2** *
   *     **PAN** * **PhoneNumber**
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID identificationType(IdentificationType identificationType) {
    this.identificationType = identificationType;
    return this;
  }

  /**
   * Type of account identification. In a request message, it informs the POI System the type of the
   * account or card identification, when provided by the Sale Terminal. (e.g. because the card
   * information is a barcode read by the Cashier on a scanner device). In a response message, it
   * informs the Sale System the type of the account or card identification. Possible values: *
   * **AccountNumber** * **BarCode** * **ISOTrack2** * **PAN** * **PhoneNumber**
   *
   * @return identificationType Type of account identification. In a request message, it informs the
   *     POI System the type of the account or card identification, when provided by the Sale
   *     Terminal. (e.g. because the card information is a barcode read by the Cashier on a scanner
   *     device). In a response message, it informs the Sale System the type of the account or card
   *     identification. Possible values: * **AccountNumber** * **BarCode** * **ISOTrack2** *
   *     **PAN** * **PhoneNumber**
   */
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IdentificationType getIdentificationType() {
    return identificationType;
  }

  /**
   * Type of account identification. In a request message, it informs the POI System the type of the
   * account or card identification, when provided by the Sale Terminal. (e.g. because the card
   * information is a barcode read by the Cashier on a scanner device). In a response message, it
   * informs the Sale System the type of the account or card identification. Possible values: *
   * **AccountNumber** * **BarCode** * **ISOTrack2** * **PAN** * **PhoneNumber**
   *
   * @param identificationType Type of account identification. In a request message, it informs the
   *     POI System the type of the account or card identification, when provided by the Sale
   *     Terminal. (e.g. because the card information is a barcode read by the Cashier on a scanner
   *     device). In a response message, it informs the Sale System the type of the account or card
   *     identification. Possible values: * **AccountNumber** * **BarCode** * **ISOTrack2** *
   *     **PAN** * **PhoneNumber**
   */
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationType(IdentificationType identificationType) {
    this.identificationType = identificationType;
  }

  /**
   * Stored value account identification. The identification of the stored value account conforming
   * to the IdentificationType.
   *
   * @param storedValueID Stored value account identification. The identification of the stored
   *     value account conforming to the IdentificationType.
   * @return the current {@code StoredValueAccountID} instance, allowing for method chaining
   */
  public StoredValueAccountID storedValueID(String storedValueID) {
    this.storedValueID = storedValueID;
    return this;
  }

  /**
   * Stored value account identification. The identification of the stored value account conforming
   * to the IdentificationType.
   *
   * @return storedValueID Stored value account identification. The identification of the stored
   *     value account conforming to the IdentificationType.
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStoredValueID() {
    return storedValueID;
  }

  /**
   * Stored value account identification. The identification of the stored value account conforming
   * to the IdentificationType.
   *
   * @param storedValueID Stored value account identification. The identification of the stored
   *     value account conforming to the IdentificationType.
   */
  @JsonProperty(JSON_PROPERTY_STORED_VALUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoredValueID(String storedValueID) {
    this.storedValueID = storedValueID;
  }

  /** Return true if this StoredValueAccountID object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoredValueAccountID storedValueAccountID = (StoredValueAccountID) o;
    return Objects.equals(this.storedValueAccountType, storedValueAccountID.storedValueAccountType)
        && Objects.equals(this.storedValueProvider, storedValueAccountID.storedValueProvider)
        && Objects.equals(this.ownerName, storedValueAccountID.ownerName)
        && Objects.equals(this.expiryDate, storedValueAccountID.expiryDate)
        && Objects.equals(this.entryMode, storedValueAccountID.entryMode)
        && Objects.equals(this.identificationType, storedValueAccountID.identificationType)
        && Objects.equals(this.storedValueID, storedValueAccountID.storedValueID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        storedValueAccountType,
        storedValueProvider,
        ownerName,
        expiryDate,
        entryMode,
        identificationType,
        storedValueID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoredValueAccountID {\n");
    sb.append("    storedValueAccountType: ")
        .append(toIndentedString(storedValueAccountType))
        .append("\n");
    sb.append("    storedValueProvider: ")
        .append(toIndentedString(storedValueProvider))
        .append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    entryMode: ").append(toIndentedString(entryMode)).append("\n");
    sb.append("    identificationType: ").append(toIndentedString(identificationType)).append("\n");
    sb.append("    storedValueID: ").append(toIndentedString(storedValueID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create an instance of StoredValueAccountID given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StoredValueAccountID
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     StoredValueAccountID
   */
  public static StoredValueAccountID fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, StoredValueAccountID.class);
  }

  /**
   * Convert an instance of StoredValueAccountID to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
