/*
 * Legal Entity Management API
 *
 * The version of the OpenAPI document: 4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.legalentitymanagement;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import java.util.*;
import java.util.logging.Logger;
import com.adyen.model.legalentitymanagement.PhoneNumber;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * Support
 */
@JsonPropertyOrder({
  Support.JSON_PROPERTY_EMAIL,
  Support.JSON_PROPERTY_PHONE
})

public class Support {
  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetEmail = false;

    public static final String JSON_PROPERTY_PHONE = "phone";
  private PhoneNumber phone;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPhone = false;

   
  /** Sets whether attributes with null values should be explicitly included in the JSON payload. Default is false. */
  @JsonIgnore
  private boolean includeNullValues = false;

  public Support() { 
  }

  /**
   * The support email address of the legal entity. Required if you have a platform setup.
   *
   * @param email The support email address of the legal entity. Required if you have a platform setup.
   * @return the current {@code Support} instance, allowing for method chaining
   */
  public Support email(String email) {
    this.email = email;
    isSetEmail = true; // mark as set
    return this;
  }

  /**
   * The support email address of the legal entity. Required if you have a platform setup.
   * @return email The support email address of the legal entity. Required if you have a platform setup.
   */
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }

  /**
   * The support email address of the legal entity. Required if you have a platform setup.
   *
   * @param email The support email address of the legal entity. Required if you have a platform setup.
   */
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
    isSetEmail = true; // mark as set
  }
  
  /**
   * phone
   *
   * @param phone 
   * @return the current {@code Support} instance, allowing for method chaining
   */
  public Support phone(PhoneNumber phone) {
    this.phone = phone;
    isSetPhone = true; // mark as set
    return this;
  }

  /**
   * Get phone
   * @return phone 
   */
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PhoneNumber getPhone() {
    return phone;
  }

  /**
   * phone
   *
   * @param phone 
   */
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(PhoneNumber phone) {
    this.phone = phone;
    isSetPhone = true; // mark as set
  }
  

  /** Configures whether null values are explicitly serialized in the JSON payload. Default is false. */
  public Support includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /** Sets whether null values should be explicitly serialized in the JSON payload. Default is false. */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }


  /**
   * Return true if this Support object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Support support = (Support) o;
    return Objects.equals(this.email, support.email) &&
        Objects.equals(this.isSetEmail, support.isSetEmail) &&
        Objects.equals(this.phone, support.phone) &&
        Objects.equals(this.isSetPhone, support.isSetPhone)
    ;
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, isSetEmail, phone, isSetPhone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Support {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetEmail) {
      addIfNull(nulls, JSON_PROPERTY_EMAIL, this.email);
    }
    if (isSetPhone) {
      addIfNull(nulls, JSON_PROPERTY_PHONE, this.phone);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

/**
   * Create an instance of Support given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Support
   * @throws JsonProcessingException if the JSON string is invalid with respect to Support
   */
  public static Support fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, Support.class);
  }
/**
  * Convert an instance of Support to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
