/*
 * Configuration webhooks
 *
 * The version of the OpenAPI document: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.configurationwebhooks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.Arrays;
import java.util.logging.Logger;

/** WebhookTopUpConfiguration */
@JsonPropertyOrder({
  WebhookTopUpConfiguration.JSON_PROPERTY_COUNTERPARTY,
  WebhookTopUpConfiguration.JSON_PROPERTY_DESCRIPTION,
  WebhookTopUpConfiguration.JSON_PROPERTY_ID,
  WebhookTopUpConfiguration.JSON_PROPERTY_MANDATE,
  WebhookTopUpConfiguration.JSON_PROPERTY_REFERENCE_FOR_BENEFICIARY,
  WebhookTopUpConfiguration.JSON_PROPERTY_STATUS,
  WebhookTopUpConfiguration.JSON_PROPERTY_TOP_UP_AMOUNT,
  WebhookTopUpConfiguration.JSON_PROPERTY_TRIGGER
})
public class WebhookTopUpConfiguration {
  public static final String JSON_PROPERTY_COUNTERPARTY = "counterparty";
  private WebhookTopUpCounterparty counterparty;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_MANDATE = "mandate";
  private WebhookTopUpMandate mandate;

  public static final String JSON_PROPERTY_REFERENCE_FOR_BENEFICIARY = "referenceForBeneficiary";
  private String referenceForBeneficiary;

  /**
   * The status of the top-up configuration. Possible values: * **active**: the top-up is enabled
   * and funds are pulled in. * **inactive**: the top-up is disabled and cannot be triggered.
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),

    INACTIVE(String.valueOf("inactive"));

    private static final Logger LOG = Logger.getLogger(StatusEnum.class.getName());

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      // handling unexpected value
      LOG.warning(
          "StatusEnum: unexpected enum value '"
              + value
              + "' - Supported values are "
              + Arrays.toString(StatusEnum.values()));
      return null;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_TOP_UP_AMOUNT = "topUpAmount";
  private WebhookTopUpAmount topUpAmount;

  public static final String JSON_PROPERTY_TRIGGER = "trigger";
  private WebhookTopUpTrigger trigger;

  public WebhookTopUpConfiguration() {}

  /**
   * counterparty
   *
   * @param counterparty
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration counterparty(WebhookTopUpCounterparty counterparty) {
    this.counterparty = counterparty;
    return this;
  }

  /**
   * Get counterparty
   *
   * @return counterparty
   */
  @JsonProperty(JSON_PROPERTY_COUNTERPARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookTopUpCounterparty getCounterparty() {
    return counterparty;
  }

  /**
   * counterparty
   *
   * @param counterparty
   */
  @JsonProperty(JSON_PROPERTY_COUNTERPARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCounterparty(WebhookTopUpCounterparty counterparty) {
    this.counterparty = counterparty;
  }

  /**
   * The message that is used in the top-up transfer&#39;s description body with a maximum length of
   * 140 characters. If the message is longer after replacing placeholders, the message is cut off
   * at 140 characters.
   *
   * @param description The message that is used in the top-up transfer&#39;s description body with
   *     a maximum length of 140 characters. If the message is longer after replacing placeholders,
   *     the message is cut off at 140 characters.
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration description(String description) {
    this.description = description;
    return this;
  }

  /**
   * The message that is used in the top-up transfer&#39;s description body with a maximum length of
   * 140 characters. If the message is longer after replacing placeholders, the message is cut off
   * at 140 characters.
   *
   * @return description The message that is used in the top-up transfer&#39;s description body with
   *     a maximum length of 140 characters. If the message is longer after replacing placeholders,
   *     the message is cut off at 140 characters.
   */
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }

  /**
   * The message that is used in the top-up transfer&#39;s description body with a maximum length of
   * 140 characters. If the message is longer after replacing placeholders, the message is cut off
   * at 140 characters.
   *
   * @param description The message that is used in the top-up transfer&#39;s description body with
   *     a maximum length of 140 characters. If the message is longer after replacing placeholders,
   *     the message is cut off at 140 characters.
   */
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * The unique identifier of the recurring top-up configuration.
   *
   * @param id The unique identifier of the recurring top-up configuration.
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the recurring top-up configuration.
   *
   * @return id The unique identifier of the recurring top-up configuration.
   */
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }

  /**
   * The unique identifier of the recurring top-up configuration.
   *
   * @param id The unique identifier of the recurring top-up configuration.
   */
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }

  /**
   * mandate
   *
   * @param mandate
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration mandate(WebhookTopUpMandate mandate) {
    this.mandate = mandate;
    return this;
  }

  /**
   * Get mandate
   *
   * @return mandate
   */
  @JsonProperty(JSON_PROPERTY_MANDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookTopUpMandate getMandate() {
    return mandate;
  }

  /**
   * mandate
   *
   * @param mandate
   */
  @JsonProperty(JSON_PROPERTY_MANDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMandate(WebhookTopUpMandate mandate) {
    this.mandate = mandate;
  }

  /**
   * A reference that is sent to the recipient. This reference is also sent in all webhooks related
   * to the transfer, so you can use it to track statuses for both parties involved in the funds
   * movement. Supported characters: **a-z**, **A-Z**, **0-9**.
   *
   * @param referenceForBeneficiary A reference that is sent to the recipient. This reference is
   *     also sent in all webhooks related to the transfer, so you can use it to track statuses for
   *     both parties involved in the funds movement. Supported characters: **a-z**, **A-Z**,
   *     **0-9**.
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration referenceForBeneficiary(String referenceForBeneficiary) {
    this.referenceForBeneficiary = referenceForBeneficiary;
    return this;
  }

  /**
   * A reference that is sent to the recipient. This reference is also sent in all webhooks related
   * to the transfer, so you can use it to track statuses for both parties involved in the funds
   * movement. Supported characters: **a-z**, **A-Z**, **0-9**.
   *
   * @return referenceForBeneficiary A reference that is sent to the recipient. This reference is
   *     also sent in all webhooks related to the transfer, so you can use it to track statuses for
   *     both parties involved in the funds movement. Supported characters: **a-z**, **A-Z**,
   *     **0-9**.
   */
  @JsonProperty(JSON_PROPERTY_REFERENCE_FOR_BENEFICIARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReferenceForBeneficiary() {
    return referenceForBeneficiary;
  }

  /**
   * A reference that is sent to the recipient. This reference is also sent in all webhooks related
   * to the transfer, so you can use it to track statuses for both parties involved in the funds
   * movement. Supported characters: **a-z**, **A-Z**, **0-9**.
   *
   * @param referenceForBeneficiary A reference that is sent to the recipient. This reference is
   *     also sent in all webhooks related to the transfer, so you can use it to track statuses for
   *     both parties involved in the funds movement. Supported characters: **a-z**, **A-Z**,
   *     **0-9**.
   */
  @JsonProperty(JSON_PROPERTY_REFERENCE_FOR_BENEFICIARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceForBeneficiary(String referenceForBeneficiary) {
    this.referenceForBeneficiary = referenceForBeneficiary;
  }

  /**
   * The status of the top-up configuration. Possible values: * **active**: the top-up is enabled
   * and funds are pulled in. * **inactive**: the top-up is disabled and cannot be triggered.
   *
   * @param status The status of the top-up configuration. Possible values: * **active**: the top-up
   *     is enabled and funds are pulled in. * **inactive**: the top-up is disabled and cannot be
   *     triggered.
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the top-up configuration. Possible values: * **active**: the top-up is enabled
   * and funds are pulled in. * **inactive**: the top-up is disabled and cannot be triggered.
   *
   * @return status The status of the top-up configuration. Possible values: * **active**: the
   *     top-up is enabled and funds are pulled in. * **inactive**: the top-up is disabled and
   *     cannot be triggered.
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * The status of the top-up configuration. Possible values: * **active**: the top-up is enabled
   * and funds are pulled in. * **inactive**: the top-up is disabled and cannot be triggered.
   *
   * @param status The status of the top-up configuration. Possible values: * **active**: the top-up
   *     is enabled and funds are pulled in. * **inactive**: the top-up is disabled and cannot be
   *     triggered.
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  /**
   * topUpAmount
   *
   * @param topUpAmount
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration topUpAmount(WebhookTopUpAmount topUpAmount) {
    this.topUpAmount = topUpAmount;
    return this;
  }

  /**
   * Get topUpAmount
   *
   * @return topUpAmount
   */
  @JsonProperty(JSON_PROPERTY_TOP_UP_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookTopUpAmount getTopUpAmount() {
    return topUpAmount;
  }

  /**
   * topUpAmount
   *
   * @param topUpAmount
   */
  @JsonProperty(JSON_PROPERTY_TOP_UP_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopUpAmount(WebhookTopUpAmount topUpAmount) {
    this.topUpAmount = topUpAmount;
  }

  /**
   * trigger
   *
   * @param trigger
   * @return the current {@code WebhookTopUpConfiguration} instance, allowing for method chaining
   */
  public WebhookTopUpConfiguration trigger(WebhookTopUpTrigger trigger) {
    this.trigger = trigger;
    return this;
  }

  /**
   * Get trigger
   *
   * @return trigger
   */
  @JsonProperty(JSON_PROPERTY_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookTopUpTrigger getTrigger() {
    return trigger;
  }

  /**
   * trigger
   *
   * @param trigger
   */
  @JsonProperty(JSON_PROPERTY_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrigger(WebhookTopUpTrigger trigger) {
    this.trigger = trigger;
  }

  /** Return true if this WebhookTopUpConfiguration object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookTopUpConfiguration webhookTopUpConfiguration = (WebhookTopUpConfiguration) o;
    return Objects.equals(this.counterparty, webhookTopUpConfiguration.counterparty)
        && Objects.equals(this.description, webhookTopUpConfiguration.description)
        && Objects.equals(this.id, webhookTopUpConfiguration.id)
        && Objects.equals(this.mandate, webhookTopUpConfiguration.mandate)
        && Objects.equals(
            this.referenceForBeneficiary, webhookTopUpConfiguration.referenceForBeneficiary)
        && Objects.equals(this.status, webhookTopUpConfiguration.status)
        && Objects.equals(this.topUpAmount, webhookTopUpConfiguration.topUpAmount)
        && Objects.equals(this.trigger, webhookTopUpConfiguration.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        counterparty,
        description,
        id,
        mandate,
        referenceForBeneficiary,
        status,
        topUpAmount,
        trigger);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookTopUpConfiguration {\n");
    sb.append("    counterparty: ").append(toIndentedString(counterparty)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mandate: ").append(toIndentedString(mandate)).append("\n");
    sb.append("    referenceForBeneficiary: ")
        .append(toIndentedString(referenceForBeneficiary))
        .append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    topUpAmount: ").append(toIndentedString(topUpAmount)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Create an instance of WebhookTopUpConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookTopUpConfiguration
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     WebhookTopUpConfiguration
   */
  public static WebhookTopUpConfiguration fromJson(String jsonString)
      throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, WebhookTopUpConfiguration.class);
  }

  /**
   * Convert an instance of WebhookTopUpConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
