/*
 * Adyen BinLookup API
 *
 * The version of the OpenAPI document: 54
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.binlookup;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import java.util.*;
import java.util.logging.Logger;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;


/**
 * MerchantDetails
 */
@JsonPropertyOrder({
  MerchantDetails.JSON_PROPERTY_COUNTRY_CODE,
  MerchantDetails.JSON_PROPERTY_ENROLLED_IN3_D_SECURE,
  MerchantDetails.JSON_PROPERTY_MCC
})

public class MerchantDetails {
  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  private String countryCode;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetCountryCode = false;

    public static final String JSON_PROPERTY_ENROLLED_IN3_D_SECURE = "enrolledIn3DSecure";
  private Boolean enrolledIn3DSecure;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetEnrolledIn3DSecure = false;

    public static final String JSON_PROPERTY_MCC = "mcc";
  private String mcc;
  /** Mark when the attribute has been explicitly set. */
  private boolean isSetMcc = false;

   
  /** Sets whether attributes with null values should be explicitly included in the JSON payload. Default is false. */
  @JsonIgnore
  private boolean includeNullValues = false;

  public MerchantDetails() { 
  }

  /**
   * 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   *
   * @param countryCode 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   * @return the current {@code MerchantDetails} instance, allowing for method chaining
   */
  public MerchantDetails countryCode(String countryCode) {
    this.countryCode = countryCode;
    isSetCountryCode = true; // mark as set
    return this;
  }

  /**
   * 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   * @return countryCode 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   */
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountryCode() {
    return countryCode;
  }

  /**
   * 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   *
   * @param countryCode 2-letter ISO 3166 country code of the card acceptor location. &gt; This parameter is required for the merchants who don&#39;t use Adyen as the payment authorisation gateway.
   */
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
    isSetCountryCode = true; // mark as set
  }
  
  /**
   * If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   *
   * @param enrolledIn3DSecure If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   * @return the current {@code MerchantDetails} instance, allowing for method chaining
   */
  public MerchantDetails enrolledIn3DSecure(Boolean enrolledIn3DSecure) {
    this.enrolledIn3DSecure = enrolledIn3DSecure;
    isSetEnrolledIn3DSecure = true; // mark as set
    return this;
  }

  /**
   * If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   * @return enrolledIn3DSecure If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   */
  @JsonProperty(JSON_PROPERTY_ENROLLED_IN3_D_SECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnrolledIn3DSecure() {
    return enrolledIn3DSecure;
  }

  /**
   * If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   *
   * @param enrolledIn3DSecure If true, indicates that the merchant is enrolled in 3D Secure for the card network.
   */
  @JsonProperty(JSON_PROPERTY_ENROLLED_IN3_D_SECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnrolledIn3DSecure(Boolean enrolledIn3DSecure) {
    this.enrolledIn3DSecure = enrolledIn3DSecure;
    isSetEnrolledIn3DSecure = true; // mark as set
  }
  
  /**
   * The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   *
   * @param mcc The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   * @return the current {@code MerchantDetails} instance, allowing for method chaining
   */
  public MerchantDetails mcc(String mcc) {
    this.mcc = mcc;
    isSetMcc = true; // mark as set
    return this;
  }

  /**
   * The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   * @return mcc The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   */
  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMcc() {
    return mcc;
  }

  /**
   * The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   *
   * @param mcc The merchant category code (MCC) is a four-digit number which relates to a particular market segment. This code reflects the predominant activity that is conducted by the merchant.  The list of MCCs can be found [here](https://en.wikipedia.org/wiki/Merchant_category_code).
   */
  @JsonProperty(JSON_PROPERTY_MCC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMcc(String mcc) {
    this.mcc = mcc;
    isSetMcc = true; // mark as set
  }
  

  /** Configures whether null values are explicitly serialized in the JSON payload. Default is false. */
  public MerchantDetails includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /** Sets whether null values should be explicitly serialized in the JSON payload. Default is false. */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }


  /**
   * Return true if this MerchantDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantDetails merchantDetails = (MerchantDetails) o;
    return Objects.equals(this.countryCode, merchantDetails.countryCode) &&
        Objects.equals(this.isSetCountryCode, merchantDetails.isSetCountryCode) &&
        Objects.equals(this.enrolledIn3DSecure, merchantDetails.enrolledIn3DSecure) &&
        Objects.equals(this.isSetEnrolledIn3DSecure, merchantDetails.isSetEnrolledIn3DSecure) &&
        Objects.equals(this.mcc, merchantDetails.mcc) &&
        Objects.equals(this.isSetMcc, merchantDetails.isSetMcc)
    ;
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, isSetCountryCode, enrolledIn3DSecure, isSetEnrolledIn3DSecure, mcc, isSetMcc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantDetails {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    enrolledIn3DSecure: ").append(toIndentedString(enrolledIn3DSecure)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetCountryCode) {
      addIfNull(nulls, JSON_PROPERTY_COUNTRY_CODE, this.countryCode);
    }
    if (isSetEnrolledIn3DSecure) {
      addIfNull(nulls, JSON_PROPERTY_ENROLLED_IN3_D_SECURE, this.enrolledIn3DSecure);
    }
    if (isSetMcc) {
      addIfNull(nulls, JSON_PROPERTY_MCC, this.mcc);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

/**
   * Create an instance of MerchantDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MerchantDetails
   * @throws JsonProcessingException if the JSON string is invalid with respect to MerchantDetails
   */
  public static MerchantDetails fromJson(String jsonString) throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, MerchantDetails.class);
  }
/**
  * Convert an instance of MerchantDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
