/*
 * Adyen Checkout API
 *
 * The version of the OpenAPI document: 71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adyen.model.checkout;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import java.util.Arrays;
import java.util.logging.Logger;

/** StandalonePaymentCancelResponse */
@JsonPropertyOrder({
  StandalonePaymentCancelResponse.JSON_PROPERTY_MERCHANT_ACCOUNT,
  StandalonePaymentCancelResponse.JSON_PROPERTY_PAYMENT_REFERENCE,
  StandalonePaymentCancelResponse.JSON_PROPERTY_PSP_REFERENCE,
  StandalonePaymentCancelResponse.JSON_PROPERTY_REFERENCE,
  StandalonePaymentCancelResponse.JSON_PROPERTY_STATUS
})
public class StandalonePaymentCancelResponse {
  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT = "merchantAccount";
  private String merchantAccount;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetMerchantAccount = false;

  public static final String JSON_PROPERTY_PAYMENT_REFERENCE = "paymentReference";
  private String paymentReference;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPaymentReference = false;

  public static final String JSON_PROPERTY_PSP_REFERENCE = "pspReference";
  private String pspReference;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetPspReference = false;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetReference = false;

  /** The status of your request. This will always have the value **received**. */
  public enum StatusEnum {
    RECEIVED(String.valueOf("received"));

    private static final Logger LOG = Logger.getLogger(StatusEnum.class.getName());

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      // handling unexpected value
      LOG.warning(
          "StatusEnum: unexpected enum value '"
              + value
              + "' - Supported values are "
              + Arrays.toString(StatusEnum.values()));
      return null;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  /** Mark when the attribute has been explicitly set. */
  private boolean isSetStatus = false;

  /**
   * Sets whether attributes with null values should be explicitly included in the JSON payload.
   * Default is false.
   */
  @JsonIgnore private boolean includeNullValues = false;

  public StandalonePaymentCancelResponse() {}

  /**
   * The merchant account that is used to process the payment.
   *
   * @param merchantAccount The merchant account that is used to process the payment.
   * @return the current {@code StandalonePaymentCancelResponse} instance, allowing for method
   *     chaining
   */
  public StandalonePaymentCancelResponse merchantAccount(String merchantAccount) {
    this.merchantAccount = merchantAccount;
    isSetMerchantAccount = true; // mark as set
    return this;
  }

  /**
   * The merchant account that is used to process the payment.
   *
   * @return merchantAccount The merchant account that is used to process the payment.
   */
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantAccount() {
    return merchantAccount;
  }

  /**
   * The merchant account that is used to process the payment.
   *
   * @param merchantAccount The merchant account that is used to process the payment.
   */
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccount(String merchantAccount) {
    this.merchantAccount = merchantAccount;
    isSetMerchantAccount = true; // mark as set
  }

  /**
   * The
   * [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   * of the payment to cancel.
   *
   * @param paymentReference The
   *     [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   *     of the payment to cancel.
   * @return the current {@code StandalonePaymentCancelResponse} instance, allowing for method
   *     chaining
   */
  public StandalonePaymentCancelResponse paymentReference(String paymentReference) {
    this.paymentReference = paymentReference;
    isSetPaymentReference = true; // mark as set
    return this;
  }

  /**
   * The
   * [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   * of the payment to cancel.
   *
   * @return paymentReference The
   *     [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   *     of the payment to cancel.
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPaymentReference() {
    return paymentReference;
  }

  /**
   * The
   * [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   * of the payment to cancel.
   *
   * @param paymentReference The
   *     [&#x60;reference&#x60;](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_reference)
   *     of the payment to cancel.
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentReference(String paymentReference) {
    this.paymentReference = paymentReference;
    isSetPaymentReference = true; // mark as set
  }

  /**
   * Adyen&#39;s 16-character reference associated with the cancel request.
   *
   * @param pspReference Adyen&#39;s 16-character reference associated with the cancel request.
   * @return the current {@code StandalonePaymentCancelResponse} instance, allowing for method
   *     chaining
   */
  public StandalonePaymentCancelResponse pspReference(String pspReference) {
    this.pspReference = pspReference;
    isSetPspReference = true; // mark as set
    return this;
  }

  /**
   * Adyen&#39;s 16-character reference associated with the cancel request.
   *
   * @return pspReference Adyen&#39;s 16-character reference associated with the cancel request.
   */
  @JsonProperty(JSON_PROPERTY_PSP_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPspReference() {
    return pspReference;
  }

  /**
   * Adyen&#39;s 16-character reference associated with the cancel request.
   *
   * @param pspReference Adyen&#39;s 16-character reference associated with the cancel request.
   */
  @JsonProperty(JSON_PROPERTY_PSP_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPspReference(String pspReference) {
    this.pspReference = pspReference;
    isSetPspReference = true; // mark as set
  }

  /**
   * Your reference for the cancel request.
   *
   * @param reference Your reference for the cancel request.
   * @return the current {@code StandalonePaymentCancelResponse} instance, allowing for method
   *     chaining
   */
  public StandalonePaymentCancelResponse reference(String reference) {
    this.reference = reference;
    isSetReference = true; // mark as set
    return this;
  }

  /**
   * Your reference for the cancel request.
   *
   * @return reference Your reference for the cancel request.
   */
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReference() {
    return reference;
  }

  /**
   * Your reference for the cancel request.
   *
   * @param reference Your reference for the cancel request.
   */
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference(String reference) {
    this.reference = reference;
    isSetReference = true; // mark as set
  }

  /**
   * The status of your request. This will always have the value **received**.
   *
   * @param status The status of your request. This will always have the value **received**.
   * @return the current {@code StandalonePaymentCancelResponse} instance, allowing for method
   *     chaining
   */
  public StandalonePaymentCancelResponse status(StatusEnum status) {
    this.status = status;
    isSetStatus = true; // mark as set
    return this;
  }

  /**
   * The status of your request. This will always have the value **received**.
   *
   * @return status The status of your request. This will always have the value **received**.
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * The status of your request. This will always have the value **received**.
   *
   * @param status The status of your request. This will always have the value **received**.
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
    isSetStatus = true; // mark as set
  }

  /**
   * Configures whether null values are explicitly serialized in the JSON payload. Default is false.
   */
  public StandalonePaymentCancelResponse includeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
    return this;
  }

  /** Returns whether null values are explicitly serialized in the JSON payload. */
  public boolean isIncludeNullValues() {
    return includeNullValues;
  }

  /**
   * Sets whether null values should be explicitly serialized in the JSON payload. Default is false.
   */
  public void setIncludeNullValues(boolean includeNullValues) {
    this.includeNullValues = includeNullValues;
  }

  /** Return true if this StandalonePaymentCancelResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandalonePaymentCancelResponse standalonePaymentCancelResponse =
        (StandalonePaymentCancelResponse) o;
    return Objects.equals(this.merchantAccount, standalonePaymentCancelResponse.merchantAccount)
        && Objects.equals(
            this.isSetMerchantAccount, standalonePaymentCancelResponse.isSetMerchantAccount)
        && Objects.equals(this.paymentReference, standalonePaymentCancelResponse.paymentReference)
        && Objects.equals(
            this.isSetPaymentReference, standalonePaymentCancelResponse.isSetPaymentReference)
        && Objects.equals(this.pspReference, standalonePaymentCancelResponse.pspReference)
        && Objects.equals(this.isSetPspReference, standalonePaymentCancelResponse.isSetPspReference)
        && Objects.equals(this.reference, standalonePaymentCancelResponse.reference)
        && Objects.equals(this.isSetReference, standalonePaymentCancelResponse.isSetReference)
        && Objects.equals(this.status, standalonePaymentCancelResponse.status)
        && Objects.equals(this.isSetStatus, standalonePaymentCancelResponse.isSetStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        merchantAccount,
        isSetMerchantAccount,
        paymentReference,
        isSetPaymentReference,
        pspReference,
        isSetPspReference,
        reference,
        isSetReference,
        status,
        isSetStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandalonePaymentCancelResponse {\n");
    sb.append("    merchantAccount: ").append(toIndentedString(merchantAccount)).append("\n");
    sb.append("    paymentReference: ").append(toIndentedString(paymentReference)).append("\n");
    sb.append("    pspReference: ").append(toIndentedString(pspReference)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /** Returns a map of properties to be merged into the JSON payload as explicit null values. */
  @JsonInclude(JsonInclude.Include.ALWAYS)
  @JsonAnyGetter
  public Map<String, Object> getExplicitNulls() {
    if (!this.includeNullValues) {
      return Collections.emptyMap();
    }

    Map<String, Object> nulls = new HashMap<>();

    if (isSetMerchantAccount) {
      addIfNull(nulls, JSON_PROPERTY_MERCHANT_ACCOUNT, this.merchantAccount);
    }
    if (isSetPaymentReference) {
      addIfNull(nulls, JSON_PROPERTY_PAYMENT_REFERENCE, this.paymentReference);
    }
    if (isSetPspReference) {
      addIfNull(nulls, JSON_PROPERTY_PSP_REFERENCE, this.pspReference);
    }
    if (isSetReference) {
      addIfNull(nulls, JSON_PROPERTY_REFERENCE, this.reference);
    }
    if (isSetStatus) {
      addIfNull(nulls, JSON_PROPERTY_STATUS, this.status);
    }

    return nulls;
  }

  // add to map when value is null
  private void addIfNull(Map<String, Object> map, String key, Object value) {
    if (value == null) {
      map.put(key, null);
    }
  }

  /**
   * Create an instance of StandalonePaymentCancelResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StandalonePaymentCancelResponse
   * @throws JsonProcessingException if the JSON string is invalid with respect to
   *     StandalonePaymentCancelResponse
   */
  public static StandalonePaymentCancelResponse fromJson(String jsonString)
      throws JsonProcessingException {
    return JSON.getMapper().readValue(jsonString, StandalonePaymentCancelResponse.class);
  }

  /**
   * Convert an instance of StandalonePaymentCancelResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() throws JsonProcessingException {
    return JSON.getMapper().writeValueAsString(this);
  }
}
