name: Github Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gh_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
#      - name: Get the release script
#        run: |
#          wget https://raw.githubusercontent.com/Adyen/adyen-node-api-library/develop/.github/scripts/release.js -P ./.github/scripts
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
      - name: Grab version
        uses: actions/github-script@v6
        id: release
        with:
          script: |
            const release = require('./.github/scripts/release.js')
            core.setOutput('version', release.pomJavaVersion())
      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
        run: |
          gh release create v${{steps.release.outputs.version}} \
            --title 'Adyen Python API Library v${{steps.release.outputs.version}}' \
            --generate-notes --target main
#      - name: Delete the release script
#        run: |
#          rm -f ./.github/scripts/release.js
      - name: Update develop branch
        run: |
          git checkout develop
          git merge main
          git push origin develop